FROM node:20-alpine AS dev

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 5172
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# --- production build ---
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
