# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collector/proto/telemetry.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'collector/proto/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ollector/proto/telemetry.proto\x12\x16plantrace.telemetry.v1\"\xc2\x03\n\x13QueryTelemetryEvent\x12\x15\n\rdatabase_name\x18\x01 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x02 \x01(\t\x12\x12\n\nservice_id\x18\x03 \x01(\t\x12\x19\n\x11query_fingerprint\x18\x04 \x01(\t\x12\x16\n\x0enormalized_sql\x18\x05 \x01(\t\x12\x18\n\x10raw_query_sample\x18\x06 \x01(\t\x12\r\n\x05\x63\x61lls\x18\x07 \x01(\x03\x12\x1a\n\x12total_exec_time_ms\x18\x08 \x01(\x01\x12\x19\n\x11mean_exec_time_ms\x18\t \x01(\x01\x12\x0c\n\x04rows\x18\n \x01(\x03\x12\x17\n\x0fshared_blks_hit\x18\x0b \x01(\x03\x12\x18\n\x10shared_blks_read\x18\x0c \x01(\x03\x12\x16\n\x0etemp_blks_read\x18\r \x01(\x03\x12\x19\n\x11temp_blks_written\x18\x0e \x01(\x03\x12 \n\x18\x64\x65tected_vector_operator\x18\x0f \x01(\t\x12\x17\n\x0fis_vector_query\x18\x10 \x01(\x08\x12\x14\n\x0c\x65xplain_json\x18\x11 \x01(\t\x12\x13\n\x0b\x63\x61ptured_at\x18\x12 \x01(\t\"\xc3\x02\n\x11PlanSnapshotEvent\x12\x15\n\rdatabase_name\x18\x01 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x02 \x01(\t\x12\x12\n\nservice_id\x18\x03 \x01(\t\x12\x19\n\x11query_fingerprint\x18\x04 \x01(\t\x12\x16\n\x0enormalized_sql\x18\x05 \x01(\t\x12\x14\n\x0c\x65xplain_json\x18\x06 \x01(\t\x12\x15\n\rtop_node_type\x18\x07 \x01(\t\x12\x15\n\ruses_seq_scan\x18\x08 \x01(\x08\x12\x17\n\x0fuses_index_scan\x18\t \x01(\x08\x12\x1c\n\x14\x65stimated_total_cost\x18\n \x01(\x01\x12\x16\n\x0e\x65stimated_rows\x18\x0b \x01(\x03\x12\x13\n\x0b\x61\x63tual_rows\x18\x0c \x01(\x03\x12\x13\n\x0b\x63\x61ptured_at\x18\r \x01(\t\"\x8f\x01\n\x17\x43ollectorHeartbeatEvent\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x02 \x01(\t\x12\x15\n\rdatabase_name\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61ptured_at\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collector.proto.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYTELEMETRYEVENT']._serialized_start=60
  _globals['_QUERYTELEMETRYEVENT']._serialized_end=510
  _globals['_PLANSNAPSHOTEVENT']._serialized_start=513
  _globals['_PLANSNAPSHOTEVENT']._serialized_end=836
  _globals['_COLLECTORHEARTBEATEVENT']._serialized_start=839
  _globals['_COLLECTORHEARTBEATEVENT']._serialized_end=982
# @@protoc_insertion_point(module_scope)
